# Generated by Django 4.2.1 on 2023-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='albums',
            new_name='albums_name',
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ManyToManyField(to='album.artist')),
            ],
        ),
    ]
